diff include ../flite_V26/hear2read/flite/include
diff include/cst_hrg.h ../flite_V26/hear2read/flite/include/cst_hrg.h
diff include/cst_lexicon.h ../flite_V26/hear2read/flite/include/cst_lexicon.h
diff include/cst_audio.h ../flite_V26/hear2read/flite/include/cst_audio.h
diff include/cst_item.h ../flite_V26/hear2read/flite/include/cst_item.h
diff include/cst_ffeatures.h ../flite_V26/hear2read/flite/include/cst_ffeatures.h
diff include/cst_relation.h ../flite_V26/hear2read/flite/include/cst_relation.h
diff include/flite.h ../flite_V26/hear2read/flite/include/flite.h
diff include/cst_sts.h ../flite_V26/hear2read/flite/include/cst_sts.h
diff include/cst_sigpr.h ../flite_V26/hear2read/flite/include/cst_sigpr.h
diff include/cst_args.h ../flite_V26/hear2read/flite/include/cst_args.h
diff include/cst_wchar.h ../flite_V26/hear2read/flite/include/cst_wchar.h
diff include/cst_features.h ../flite_V26/hear2read/flite/include/cst_features.h
diff include/cst_alloc.h ../flite_V26/hear2read/flite/include/cst_alloc.h
diff include/Makefile ../flite_V26/hear2read/flite/include/Makefile
diff include/cst_lts_rewrites.h ../flite_V26/hear2read/flite/include/cst_lts_rewrites.h
diff include/cst_utterance.h ../flite_V26/hear2read/flite/include/cst_utterance.h
diff include/cst_utt_utils.h ../flite_V26/hear2read/flite/include/cst_utt_utils.h
diff include/cst_clunits.h ../flite_V26/hear2read/flite/include/cst_clunits.h
diff include/cst_endian.h ../flite_V26/hear2read/flite/include/cst_endian.h
diff include/cst_val_const.h ../flite_V26/hear2read/flite/include/cst_val_const.h
diff include/cst_regex.h ../flite_V26/hear2read/flite/include/cst_regex.h
diff include/cst_cg.h ../flite_V26/hear2read/flite/include/cst_cg.h
diff include/cst_lts.h ../flite_V26/hear2read/flite/include/cst_lts.h
diff include/cst_error.h ../flite_V26/hear2read/flite/include/cst_error.h
diff include/cst_socket.h ../flite_V26/hear2read/flite/include/cst_socket.h
diff include/cst_val_defs.h ../flite_V26/hear2read/flite/include/cst_val_defs.h
diff include/cst_wave.h ../flite_V26/hear2read/flite/include/cst_wave.h
diff include/cst_diphone.h ../flite_V26/hear2read/flite/include/cst_diphone.h
diff include/cst_tokenstream.h ../flite_V26/hear2read/flite/include/cst_tokenstream.h
diff include/cst_voice.h ../flite_V26/hear2read/flite/include/cst_voice.h
diff include/cst_math.h ../flite_V26/hear2read/flite/include/cst_math.h
diff include/cst_track.h ../flite_V26/hear2read/flite/include/cst_track.h
diff include/cst_viterbi.h ../flite_V26/hear2read/flite/include/cst_viterbi.h
diff include/cst_val.h ../flite_V26/hear2read/flite/include/cst_val.h
diff include/cst_ss.h ../flite_V26/hear2read/flite/include/cst_ss.h
diff include/cst_phoneset.h ../flite_V26/hear2read/flite/include/cst_phoneset.h
diff include/cst_cart.h ../flite_V26/hear2read/flite/include/cst_cart.h
diff include/cst_string.h ../flite_V26/hear2read/flite/include/cst_string.h
diff include/cst_units.h ../flite_V26/hear2read/flite/include/cst_units.h
diff include/cst_synth.h ../flite_V26/hear2read/flite/include/cst_synth.h
diff include/flite_version.h ../flite_V26/hear2read/flite/include/flite_version.h
diff include/cst_file.h ../flite_V26/hear2read/flite/include/cst_file.h
diff COPYING ../flite_V26/hear2read/flite/COPYING
diff fliteDll.vcxproj.filters ../flite_V26/hear2read/flite/fliteDll.vcxproj.filters
diff wince ../flite_V26/hear2read/flite/wince
diff wince/flowm_main.c ../flite_V26/hear2read/flite/wince/flowm_main.c
diff wince/flowm.notes ../flite_V26/hear2read/flite/wince/flowm.notes
diff wince/flowm.rc ../flite_V26/hear2read/flite/wince/flowm.rc
diff wince/Makefile ../flite_V26/hear2read/flite/wince/Makefile
diff wince/flowm.h ../flite_V26/hear2read/flite/wince/flowm.h
diff wince/flowm.ico ../flite_V26/hear2read/flite/wince/flowm.ico
diff wince/flowm.bmp ../flite_V26/hear2read/flite/wince/flowm.bmp
diff wince/flowm_flite.c ../flite_V26/hear2read/flite/wince/flowm_flite.c
diff wince/_setup.xml ../flite_V26/hear2read/flite/wince/_setup.xml
diff config.log ../flite_V26/hear2read/flite/config.log
diff Exports.def ../flite_V26/hear2read/flite/Exports.def
diff bin ../flite_V26/hear2read/flite/bin
diff bin/flite_rename_voice ../flite_V26/hear2read/flite/bin/flite_rename_voice
diff bin/flite_cmu_us_kal ../flite_V26/hear2read/flite/bin/flite_cmu_us_kal
diff bin/flitechecks ../flite_V26/hear2read/flite/bin/flitechecks
diff bin/flite_cmu_us_rms ../flite_V26/hear2read/flite/bin/flite_cmu_us_rms
diff bin/huff_table ../flite_V26/hear2read/flite/bin/huff_table
diff bin/make_flite_feats ../flite_V26/hear2read/flite/bin/make_flite_feats
diff bin/add_flite_feats ../flite_V26/hear2read/flite/bin/add_flite_feats
diff bin/setup_flite ../flite_V26/hear2read/flite/bin/setup_flite
diff bin/clunit_prune ../flite_V26/hear2read/flite/bin/clunit_prune
diff bin/flite_cmu_us_slt ../flite_V26/hear2read/flite/bin/flite_cmu_us_slt
diff bin/flitevox_info ../flite_V26/hear2read/flite/bin/flitevox_info
diff bin/quantize_params ../flite_V26/hear2read/flite/bin/quantize_params
diff bin/a2byte.pl ../flite_V26/hear2read/flite/bin/a2byte.pl
diff bin/run_flitecheck ../flite_V26/hear2read/flite/bin/run_flitecheck
diff bin/flite_sort ../flite_V26/hear2read/flite/bin/flite_sort
diff bin/compile_regexes ../flite_V26/hear2read/flite/bin/compile_regexes
diff bin/wfst2c ../flite_V26/hear2read/flite/bin/wfst2c
diff bin/flite_cmu_us_awb ../flite_V26/hear2read/flite/bin/flite_cmu_us_awb
diff bin/flite ../flite_V26/hear2read/flite/bin/flite
diff bin/a2short.pl ../flite_V26/hear2read/flite/bin/a2short.pl
diff bin/make_new_lang_lex ../flite_V26/hear2read/flite/bin/make_new_lang_lex
diff bin/build_flite ../flite_V26/hear2read/flite/bin/build_flite
diff bin/t2p ../flite_V26/hear2read/flite/bin/t2p
diff bin/flite_time ../flite_V26/hear2read/flite/bin/flite_time
diff bin/build_lex ../flite_V26/hear2read/flite/bin/build_lex
diff bin/find_sts ../flite_V26/hear2read/flite/bin/find_sts
diff bin/flite_test ../flite_V26/hear2read/flite/bin/flite_test
diff bin/a2int.pl ../flite_V26/hear2read/flite/bin/a2int.pl
diff bin/flite_cmu_us_kal16 ../flite_V26/hear2read/flite/bin/flite_cmu_us_kal16
diff bin/make_voice_list ../flite_V26/hear2read/flite/bin/make_voice_list
diff bin/flite_cmu_time_awb ../flite_V26/hear2read/flite/bin/flite_cmu_time_awb
diff bin/get_voices ../flite_V26/hear2read/flite/bin/get_voices
diff bin/flite_test_fv ../flite_V26/hear2read/flite/bin/flite_test_fv
diff bin/make_lang_list ../flite_V26/hear2read/flite/bin/make_lang_list
diff android ../flite_V26/hear2read/flite/android
diff android/Makefile ../flite_V26/hear2read/flite/android/Makefile
diff android/README ../flite_V26/hear2read/flite/android/README
diff mkinstalldirs ../flite_V26/hear2read/flite/mkinstalldirs
diff sapi ../flite_V26/hear2read/flite/sapi
diff sapi/flite_sapi.sln ../flite_V26/hear2read/flite/sapi/flite_sapi.sln
diff sapi/usenglish ../flite_V26/hear2read/flite/sapi/usenglish
diff sapi/usenglish/usenglish.dsp ../flite_V26/hear2read/flite/sapi/usenglish/usenglish.dsp
diff sapi/usenglish/usenglish.vcxproj.filters ../flite_V26/hear2read/flite/sapi/usenglish/usenglish.vcxproj.filters
diff sapi/usenglish/Makefile ../flite_V26/hear2read/flite/sapi/usenglish/Makefile
diff sapi/usenglish/usenglish.vcxproj ../flite_V26/hear2read/flite/sapi/usenglish/usenglish.vcxproj
diff sapi/FliteCMUGenericCG ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG
diff sapi/FliteCMUGenericCG/resource.h ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/resource.h
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGPS.vcxproj.filters ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGPS.vcxproj.filters
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGps.def ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGps.def
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.def ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.def
diff sapi/FliteCMUGenericCG/stdafx.h ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/stdafx.h
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj.user ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj.user
diff sapi/FliteCMUGenericCG/dllmain.h ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/dllmain.h
diff sapi/FliteCMUGenericCG/Makefile ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/Makefile
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj.filters ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj.filters
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.idl ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.idl
diff sapi/FliteCMUGenericCG/dllmain.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/dllmain.cpp
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.h ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.h
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.vcxproj
diff sapi/FliteCMUGenericCG/stdafx.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/stdafx.cpp
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.cpp
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.rgs ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.rgs
diff sapi/FliteCMUGenericCG/targetver.h ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/targetver.h
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.rc ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.rc
diff sapi/FliteCMUGenericCG/FliteCMUGenericCG.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCG.cpp
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGPS.vcxproj ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGPS.vcxproj
diff sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.rgs ../flite_V26/hear2read/flite/sapi/FliteCMUGenericCG/FliteCMUGenericCGObj.rgs
diff sapi/Makefile ../flite_V26/hear2read/flite/sapi/Makefile
diff sapi/flite_sapi.dsw ../flite_V26/hear2read/flite/sapi/flite_sapi.dsw
diff sapi/README_CG ../flite_V26/hear2read/flite/sapi/README_CG
diff sapi/cmu_cg ../flite_V26/hear2read/flite/sapi/cmu_cg
diff sapi/cmu_cg/stdafx.h ../flite_V26/hear2read/flite/sapi/cmu_cg/stdafx.h
diff sapi/cmu_cg/Makefile ../flite_V26/hear2read/flite/sapi/cmu_cg/Makefile
diff sapi/cmu_cg/cmu_cg.vcxproj.user ../flite_V26/hear2read/flite/sapi/cmu_cg/cmu_cg.vcxproj.user
diff sapi/cmu_cg/stdafx.cpp ../flite_V26/hear2read/flite/sapi/cmu_cg/stdafx.cpp
diff sapi/cmu_cg/cmu_cg.vcxproj ../flite_V26/hear2read/flite/sapi/cmu_cg/cmu_cg.vcxproj
diff sapi/cmu_cg/targetver.h ../flite_V26/hear2read/flite/sapi/cmu_cg/targetver.h
diff sapi/cmu_cg/cmu_cg.vcxproj.filters ../flite_V26/hear2read/flite/sapi/cmu_cg/cmu_cg.vcxproj.filters
diff sapi/flite ../flite_V26/hear2read/flite/sapi/flite
diff sapi/flite/flite.vcxproj.filters ../flite_V26/hear2read/flite/sapi/flite/flite.vcxproj.filters
diff sapi/flite/flite.vcxproj.user ../flite_V26/hear2read/flite/sapi/flite/flite.vcxproj.user
diff sapi/flite/flite.dsp ../flite_V26/hear2read/flite/sapi/flite/flite.dsp
diff sapi/flite/flite.vcxproj ../flite_V26/hear2read/flite/sapi/flite/flite.vcxproj
diff sapi/flite/Makefile ../flite_V26/hear2read/flite/sapi/flite/Makefile
diff sapi/FliteTTSEngineObj ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj
diff sapi/FliteTTSEngineObj/FliteTTSEngineObj.cpp ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/FliteTTSEngineObj.cpp
diff sapi/FliteTTSEngineObj/FliteTTSEngineObj.h ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/FliteTTSEngineObj.h
diff sapi/FliteTTSEngineObj/Makefile ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/Makefile
diff sapi/FliteTTSEngineObj/flite_sapi_usenglish.h ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/flite_sapi_usenglish.h
diff sapi/FliteTTSEngineObj/FliteTTSEngineObj.vcxproj ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/FliteTTSEngineObj.vcxproj
diff sapi/FliteTTSEngineObj/flite_sapi_usenglish.c ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/flite_sapi_usenglish.c
diff sapi/FliteTTSEngineObj/FliteTTSEngineObj.vcxproj.filters ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/FliteTTSEngineObj.vcxproj.filters
diff sapi/FliteTTSEngineObj/FliteTTSEngineObj.dsp ../flite_V26/hear2read/flite/sapi/FliteTTSEngineObj/FliteTTSEngineObj.dsp
diff sapi/cmu_us_kal ../flite_V26/hear2read/flite/sapi/cmu_us_kal
diff sapi/cmu_us_kal/cmu_us_kal.vcxproj.filters ../flite_V26/hear2read/flite/sapi/cmu_us_kal/cmu_us_kal.vcxproj.filters
diff sapi/cmu_us_kal/cmu_us_kal.vcxproj ../flite_V26/hear2read/flite/sapi/cmu_us_kal/cmu_us_kal.vcxproj
diff sapi/cmu_us_kal/Makefile ../flite_V26/hear2read/flite/sapi/cmu_us_kal/Makefile
diff sapi/cmu_us_kal/cmu_us_kal.dsp ../flite_V26/hear2read/flite/sapi/cmu_us_kal/cmu_us_kal.dsp
diff sapi/cmulex ../flite_V26/hear2read/flite/sapi/cmulex
diff sapi/cmulex/cmulex.dsp ../flite_V26/hear2read/flite/sapi/cmulex/cmulex.dsp
diff sapi/cmulex/Makefile ../flite_V26/hear2read/flite/sapi/cmulex/Makefile
diff sapi/cmulex/cmulex.vcxproj ../flite_V26/hear2read/flite/sapi/cmulex/cmulex.vcxproj
diff sapi/cmulex/cmulex.vcxproj.filters ../flite_V26/hear2read/flite/sapi/cmulex/cmulex.vcxproj.filters
diff sapi/cmulex/cmulex.vcxproj.user ../flite_V26/hear2read/flite/sapi/cmulex/cmulex.vcxproj.user
diff sapi/FliteCMUKalDiphone ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone
diff sapi/FliteCMUKalDiphone/resource.h ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/resource.h
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj.filters ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj.filters
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj.user ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj.user
diff sapi/FliteCMUKalDiphone/register_vox ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox
diff sapi/FliteCMUKalDiphone/register_vox/register_vox.dsp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox/register_vox.dsp
diff sapi/FliteCMUKalDiphone/register_vox/register_vox.vcxproj.filters ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox/register_vox.vcxproj.filters
diff sapi/FliteCMUKalDiphone/register_vox/register_vox.vcxproj ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox/register_vox.vcxproj
diff sapi/FliteCMUKalDiphone/register_vox/Makefile ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox/Makefile
diff sapi/FliteCMUKalDiphone/register_vox/register-vox.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/register_vox/register-vox.cpp
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.rc ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.rc
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneps.def ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneps.def
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.cpp
diff sapi/FliteCMUKalDiphone/Makefile ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/Makefile
diff sapi/FliteCMUKalDiphone/StdAfx.h ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/StdAfx.h
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.vcxproj
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.dsp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.dsp
diff sapi/FliteCMUKalDiphone/StdAfx.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/StdAfx.cpp
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneps.mk ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneps.mk
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.idl ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.idl
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.rgs ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.rgs
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.h ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.h
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.def ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphone.def
diff sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.cpp ../flite_V26/hear2read/flite/sapi/FliteCMUKalDiphone/FliteCMUKalDiphoneObj.cpp
diff sapi/README ../flite_V26/hear2read/flite/sapi/README
diff temp ../flite_V26/hear2read/flite/temp
diff configure ../flite_V26/hear2read/flite/configure
diff Makefile ../flite_V26/hear2read/flite/Makefile
diff build ../flite_V26/hear2read/flite/build
diff build/x86_64-linux-gnu ../flite_V26/hear2read/flite/build/x86_64-linux-gnu
diff build/x86_64-linux-gnu/lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib
diff build/x86_64-linux-gnu/lib/libflite_cmu_indic_lex.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_indic_lex.a
diff build/x86_64-linux-gnu/lib/libflite.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite.a
diff build/x86_64-linux-gnu/lib/libflite_cmulex.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmulex.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_us_rms.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_us_rms.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_grapheme_lang.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_grapheme_lang.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_us_kal.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_us_kal.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_us_slt.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_us_slt.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_us_kal16.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_us_kal16.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_grapheme_lex.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_grapheme_lex.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_indic_lang.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_indic_lang.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_time_awb.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_time_awb.a
diff build/x86_64-linux-gnu/lib/libflite_cmu_us_awb.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_cmu_us_awb.a
diff build/x86_64-linux-gnu/lib/libflite_usenglish.a ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/lib/libflite_usenglish.a
diff build/x86_64-linux-gnu/obj ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj
diff build/x86_64-linux-gnu/obj/include ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/include
diff build/x86_64-linux-gnu/obj/main ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/main
diff build/x86_64-linux-gnu/obj/tools ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/tools
diff build/x86_64-linux-gnu/obj/lang ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_accent_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_accent_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_durmodel.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_durmodel.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_phonestate.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_phonestate.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_single_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_cg_single_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_accent.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_rms/cmu_us_rms_spamf0_accent.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_lang.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_lang.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_phoneset.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lang/cmu_grapheme_phoneset.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_lpc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_lpc.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_mcep.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_mcep.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_clunits.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_clunits.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_lex_entry.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_lex_entry.o
diff build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_time_awb/cmu_time_awb_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_durz_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_durz_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_phrasing_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_phrasing_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_f0_model.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_f0_model.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_nums_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_nums_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_int_tone_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_int_tone_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_aswd.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_aswd.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_f0lr.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_f0lr.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/usenglish.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/usenglish.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_ffeatures.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_ffeatures.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_text.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_text.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_phoneset.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_phoneset.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_gpos.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_gpos.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/.build_lib
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_pos_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_pos_cart.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_expand.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_expand.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_dur_stats.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_dur_stats.o
diff build/x86_64-linux-gnu/obj/lang/usenglish/us_int_accent_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/usenglish/us_int_accent_cart.o
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lang ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lang
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_phoneset.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_phoneset.o
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_lang.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_lang.o
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_phrasing_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lang/cmu_indic_phrasing_cart.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16 ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_res.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_res.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_lpc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_lpc.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_residx.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_residx.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_diphone.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal16/cmu_us_kal16_diphone.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_ressize.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_ressize.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_residx.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_residx.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_diphone.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_diphone.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_lpc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_lpc.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_res.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal_res.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_kal/cmu_us_kal.o
diff build/x86_64-linux-gnu/obj/lang/cmulex ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_postlex.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_postlex.o
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lts_rules.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lts_rules.o
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lts_model.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lts_model.o
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex_entries.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex_entries.o
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex.o
diff build/x86_64-linux-gnu/obj/lang/cmulex/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex_data.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmulex/cmu_lex_data.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/cmu_grapheme_lex.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/cmu_grapheme_lex.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/grapheme_unitran_tables.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/grapheme_unitran_tables.o
diff build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_grapheme_lex/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_single_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_single_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_accent_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_accent_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_accent.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_spamf0_accent.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_durmodel.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_durmodel.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_phonestate.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_slt/cmu_us_slt_cg_phonestate.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_accent.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_accent.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_phonestate.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_phonestate.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_single_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_single_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/.build_lib
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_durmodel.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_durmodel.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_accent_params.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_accent_params.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_cg.o
diff build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.o
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lex ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lex
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lex/cmu_indic_lex.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lex/cmu_indic_lex.o
diff build/x86_64-linux-gnu/obj/lang/cmu_indic_lex/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/lang/cmu_indic_lex/.build_lib
diff build/x86_64-linux-gnu/obj/src ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src
diff build/x86_64-linux-gnu/obj/src/lexicon ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/lexicon
diff build/x86_64-linux-gnu/obj/src/lexicon/cst_lts_rewrites.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/lexicon/cst_lts_rewrites.o
diff build/x86_64-linux-gnu/obj/src/lexicon/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/lexicon/.build_lib
diff build/x86_64-linux-gnu/obj/src/lexicon/cst_lexicon.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/lexicon/cst_lexicon.o
diff build/x86_64-linux-gnu/obj/src/lexicon/cst_lts.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/lexicon/cst_lts.o
diff build/x86_64-linux-gnu/obj/src/utils ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils
diff build/x86_64-linux-gnu/obj/src/utils/cst_string.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_string.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_tokenstream.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_tokenstream.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_args.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_args.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_url.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_url.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_file_stdio.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_file_stdio.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_endian.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_endian.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_socket.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_socket.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_val_const.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_val_const.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_error.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_error.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_val_user.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_val_user.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_alloc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_alloc.o
diff build/x86_64-linux-gnu/obj/src/utils/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/.build_lib
diff build/x86_64-linux-gnu/obj/src/utils/cst_mmap_posix.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_mmap_posix.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_wchar.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_wchar.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_features.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_features.o
diff build/x86_64-linux-gnu/obj/src/utils/cst_val.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/utils/cst_val.o
diff build/x86_64-linux-gnu/obj/src/wavesynth ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_sts.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_sts.o
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_sigpr.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_sigpr.o
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_reflpc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_reflpc.o
diff build/x86_64-linux-gnu/obj/src/wavesynth/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/.build_lib
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_units.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_units.o
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_clunits.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_clunits.o
diff build/x86_64-linux-gnu/obj/src/wavesynth/cst_diphone.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/wavesynth/cst_diphone.o
diff build/x86_64-linux-gnu/obj/src/synth ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth
diff build/x86_64-linux-gnu/obj/src/synth/cst_utt_utils.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_utt_utils.o
diff build/x86_64-linux-gnu/obj/src/synth/cst_ssml.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_ssml.o
diff build/x86_64-linux-gnu/obj/src/synth/cst_phoneset.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_phoneset.o
diff build/x86_64-linux-gnu/obj/src/synth/cst_synth.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_synth.o
diff build/x86_64-linux-gnu/obj/src/synth/cst_voice.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_voice.o
diff build/x86_64-linux-gnu/obj/src/synth/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/.build_lib
diff build/x86_64-linux-gnu/obj/src/synth/flite.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/flite.o
diff build/x86_64-linux-gnu/obj/src/synth/cst_ffeatures.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/synth/cst_ffeatures.o
diff build/x86_64-linux-gnu/obj/src/stats ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/stats
diff build/x86_64-linux-gnu/obj/src/stats/cst_viterbi.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/stats/cst_viterbi.o
diff build/x86_64-linux-gnu/obj/src/stats/cst_cart.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/stats/cst_cart.o
diff build/x86_64-linux-gnu/obj/src/stats/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/stats/.build_lib
diff build/x86_64-linux-gnu/obj/src/stats/cst_ss.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/stats/cst_ss.o
diff build/x86_64-linux-gnu/obj/src/audio ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio
diff build/x86_64-linux-gnu/obj/src/audio/auclient.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/auclient.o
diff build/x86_64-linux-gnu/obj/src/audio/au_streaming.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/au_streaming.o
diff build/x86_64-linux-gnu/obj/src/audio/auserver.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/auserver.o
diff build/x86_64-linux-gnu/obj/src/audio/au_oss.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/au_oss.o
diff build/x86_64-linux-gnu/obj/src/audio/audio.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/audio.o
diff build/x86_64-linux-gnu/obj/src/audio/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/audio/.build_lib
diff build/x86_64-linux-gnu/obj/src/speech ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech
diff build/x86_64-linux-gnu/obj/src/speech/cst_lpcres.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_lpcres.o
diff build/x86_64-linux-gnu/obj/src/speech/cst_wave.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_wave.o
diff build/x86_64-linux-gnu/obj/src/speech/g721.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/g721.o
diff build/x86_64-linux-gnu/obj/src/speech/cst_track_io.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_track_io.o
diff build/x86_64-linux-gnu/obj/src/speech/cst_wave_utils.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_wave_utils.o
diff build/x86_64-linux-gnu/obj/src/speech/cst_wave_io.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_wave_io.o
diff build/x86_64-linux-gnu/obj/src/speech/g723_24.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/g723_24.o
diff build/x86_64-linux-gnu/obj/src/speech/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/.build_lib
diff build/x86_64-linux-gnu/obj/src/speech/g723_40.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/g723_40.o
diff build/x86_64-linux-gnu/obj/src/speech/rateconv.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/rateconv.o
diff build/x86_64-linux-gnu/obj/src/speech/cst_track.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/cst_track.o
diff build/x86_64-linux-gnu/obj/src/speech/g72x.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/speech/g72x.o
diff build/x86_64-linux-gnu/obj/src/hrg ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg
diff build/x86_64-linux-gnu/obj/src/hrg/cst_utterance.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/cst_utterance.o
diff build/x86_64-linux-gnu/obj/src/hrg/cst_item.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/cst_item.o
diff build/x86_64-linux-gnu/obj/src/hrg/cst_relation.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/cst_relation.o
diff build/x86_64-linux-gnu/obj/src/hrg/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/.build_lib
diff build/x86_64-linux-gnu/obj/src/hrg/cst_ffeature.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/cst_ffeature.o
diff build/x86_64-linux-gnu/obj/src/hrg/cst_rel_io.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/hrg/cst_rel_io.o
diff build/x86_64-linux-gnu/obj/src/regex ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/regex
diff build/x86_64-linux-gnu/obj/src/regex/regsub.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/regex/regsub.o
diff build/x86_64-linux-gnu/obj/src/regex/regexp.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/regex/regexp.o
diff build/x86_64-linux-gnu/obj/src/regex/cst_regex.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/regex/cst_regex.o
diff build/x86_64-linux-gnu/obj/src/regex/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/regex/.build_lib
diff build/x86_64-linux-gnu/obj/src/cg ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg
diff build/x86_64-linux-gnu/obj/src/cg/cst_cg_dump_voice.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_cg_dump_voice.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_mlpg.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_mlpg.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_mlsa.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_mlsa.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_cg_map.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_cg_map.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_cg_load_voice.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_cg_load_voice.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_spamf0.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_spamf0.o
diff build/x86_64-linux-gnu/obj/src/cg/.build_lib ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/.build_lib
diff build/x86_64-linux-gnu/obj/src/cg/cst_vc.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_vc.o
diff build/x86_64-linux-gnu/obj/src/cg/cst_cg.o ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/src/cg/cst_cg.o
diff build/x86_64-linux-gnu/obj/doc ../flite_V26/hear2read/flite/build/x86_64-linux-gnu/obj/doc
diff ACKNOWLEDGEMENTS ../flite_V26/hear2read/flite/ACKNOWLEDGEMENTS
diff flite.v11.suo ../flite_V26/hear2read/flite/flite.v11.suo
diff missing ../flite_V26/hear2read/flite/missing
diff config.guess ../flite_V26/hear2read/flite/config.guess
diff install-sh ../flite_V26/hear2read/flite/install-sh
diff configure.in ../flite_V26/hear2read/flite/configure.in
diff main ../flite_V26/hear2read/flite/main
diff main/flitevox_info_main.o ../flite_V26/hear2read/flite/main/flitevox_info_main.o
diff main/t2p_main.c ../flite_V26/hear2read/flite/main/t2p_main.c
diff main/flite_voice_list.c ../flite_V26/hear2read/flite/main/flite_voice_list.c
diff main/word_times_main.c ../flite_V26/hear2read/flite/main/word_times_main.c
diff main/compile_regexes.c ../flite_V26/hear2read/flite/main/compile_regexes.c
diff main/compile_regexes.o ../flite_V26/hear2read/flite/main/compile_regexes.o
diff main/Makefile ../flite_V26/hear2read/flite/main/Makefile
diff main/flite_time_main.o ../flite_V26/hear2read/flite/main/flite_time_main.o
diff main/flitevox_info_main.c ../flite_V26/hear2read/flite/main/flitevox_info_main.c
diff main/flite_main.o ../flite_V26/hear2read/flite/main/flite_main.o
diff main/flite_lang_list.o ../flite_V26/hear2read/flite/main/flite_lang_list.o
diff main/flite_main.c ../flite_V26/hear2read/flite/main/flite_main.c
diff main/flite_lang_list.c ../flite_V26/hear2read/flite/main/flite_lang_list.c
diff main/flite_voice_list.o ../flite_V26/hear2read/flite/main/flite_voice_list.o
diff main/t2p_main.o ../flite_V26/hear2read/flite/main/t2p_main.o
diff main/flite_time_main.c ../flite_V26/hear2read/flite/main/flite_time_main.c
diff config.sub ../flite_V26/hear2read/flite/config.sub
diff config.status ../flite_V26/hear2read/flite/config.status
diff config ../flite_V26/hear2read/flite/config
diff config/android.lv ../flite_V26/hear2read/flite/config/android.lv
diff config/all.lv ../flite_V26/hear2read/flite/config/all.lv
diff config/ben.lv ../flite_V26/hear2read/flite/config/ben.lv
diff config/config.in ../flite_V26/hear2read/flite/config/config.in
diff config/Makefile ../flite_V26/hear2read/flite/config/Makefile
diff config/system.mak ../flite_V26/hear2read/flite/config/system.mak
diff config/transtac.lv ../flite_V26/hear2read/flite/config/transtac.lv
diff config/system.mak.in ../flite_V26/hear2read/flite/config/system.mak.in
diff config/common_make_rules ../flite_V26/hear2read/flite/config/common_make_rules
diff config/config ../flite_V26/hear2read/flite/config/config
diff config/project.mak ../flite_V26/hear2read/flite/config/project.mak
diff config/bolt.lv ../flite_V26/hear2read/flite/config/bolt.lv
diff config/default.lv ../flite_V26/hear2read/flite/config/default.lv
diff flite.sln ../flite_V26/hear2read/flite/flite.sln
diff tools ../flite_V26/hear2read/flite/tools
diff tools/flite_rename_voice ../flite_V26/hear2read/flite/tools/flite_rename_voice
diff tools/make_vallist.scm ../flite_V26/hear2read/flite/tools/make_vallist.scm
diff tools/find_cmimax ../flite_V26/hear2read/flite/tools/find_cmimax
diff tools/flitechecks ../flite_V26/hear2read/flite/tools/flitechecks
diff tools/huff_table ../flite_V26/hear2read/flite/tools/huff_table
diff tools/example.lex ../flite_V26/hear2read/flite/tools/example.lex
diff tools/make_flite_feats ../flite_V26/hear2read/flite/tools/make_flite_feats
diff tools/find_sts_main.o ../flite_V26/hear2read/flite/tools/find_sts_main.o
diff tools/Makefile.flite ../flite_V26/hear2read/flite/tools/Makefile.flite
diff tools/add_flite_feats ../flite_V26/hear2read/flite/tools/add_flite_feats
diff tools/Makefile.lex ../flite_V26/hear2read/flite/tools/Makefile.lex
diff tools/LANGNAME_lex.h ../flite_V26/hear2read/flite/tools/LANGNAME_lex.h
diff tools/LANGNAME_lang.h ../flite_V26/hear2read/flite/tools/LANGNAME_lang.h
diff tools/find_sts_main.c ../flite_V26/hear2read/flite/tools/find_sts_main.c
diff tools/setup_flite ../flite_V26/hear2read/flite/tools/setup_flite
diff tools/make_cg.scm ../flite_V26/hear2read/flite/tools/make_cg.scm
diff tools/make_phoneset.scm ../flite_V26/hear2read/flite/tools/make_phoneset.scm
diff tools/clunit_prune ../flite_V26/hear2read/flite/tools/clunit_prune
diff tools/Makefile.lang ../flite_V26/hear2read/flite/tools/Makefile.lang
diff tools/Makefile ../flite_V26/hear2read/flite/tools/Makefile
diff tools/play_sync.scm ../flite_V26/hear2read/flite/tools/play_sync.scm
diff tools/quantize_params ../flite_V26/hear2read/flite/tools/quantize_params
diff tools/VOICE_ldom.c ../flite_V26/hear2read/flite/tools/VOICE_ldom.c
diff tools/a2byte.pl ../flite_V26/hear2read/flite/tools/a2byte.pl
diff tools/make_cart.scm ../flite_V26/hear2read/flite/tools/make_cart.scm
diff tools/make_f0lr.scm ../flite_V26/hear2read/flite/tools/make_f0lr.scm
diff tools/run_flitecheck ../flite_V26/hear2read/flite/tools/run_flitecheck
diff tools/example.ssml ../flite_V26/hear2read/flite/tools/example.ssml
diff tools/make_clunits.scm ../flite_V26/hear2read/flite/tools/make_clunits.scm
diff tools/wfst2c ../flite_V26/hear2read/flite/tools/wfst2c
diff tools/flite_sort_main.o ../flite_V26/hear2read/flite/tools/flite_sort_main.o
diff tools/a2short.pl ../flite_V26/hear2read/flite/tools/a2short.pl
diff tools/VOICE_clunits.c ../flite_V26/hear2read/flite/tools/VOICE_clunits.c
diff tools/LANGNAME_lex.c ../flite_V26/hear2read/flite/tools/LANGNAME_lex.c
diff tools/make_didb.scm ../flite_V26/hear2read/flite/tools/make_didb.scm
diff tools/make_lts.scm ../flite_V26/hear2read/flite/tools/make_lts.scm
diff tools/make_new_lang_lex ../flite_V26/hear2read/flite/tools/make_new_lang_lex
diff tools/VOICE_cg.c ../flite_V26/hear2read/flite/tools/VOICE_cg.c
diff tools/build_flite ../flite_V26/hear2read/flite/tools/build_flite
diff tools/build_lex ../flite_V26/hear2read/flite/tools/build_lex
diff tools/LANGNAME_lang.c ../flite_V26/hear2read/flite/tools/LANGNAME_lang.c
diff tools/flite_test ../flite_V26/hear2read/flite/tools/flite_test
diff tools/a2int.pl ../flite_V26/hear2read/flite/tools/a2int.pl
diff tools/flite_sort_main.c ../flite_V26/hear2read/flite/tools/flite_sort_main.c
diff tools/make_voice_list ../flite_V26/hear2read/flite/tools/make_voice_list
diff tools/make_lts_wfst.scm ../flite_V26/hear2read/flite/tools/make_lts_wfst.scm
diff tools/VOICE_diphone.c ../flite_V26/hear2read/flite/tools/VOICE_diphone.c
diff tools/make_didb2.scm ../flite_V26/hear2read/flite/tools/make_didb2.scm
diff tools/make_ug.scm ../flite_V26/hear2read/flite/tools/make_ug.scm
diff tools/get_voices ../flite_V26/hear2read/flite/tools/get_voices
diff tools/make_lts_rewrite.scm ../flite_V26/hear2read/flite/tools/make_lts_rewrite.scm
diff tools/flite_test_fv ../flite_V26/hear2read/flite/tools/flite_test_fv
diff tools/make_lex.scm ../flite_V26/hear2read/flite/tools/make_lex.scm
diff tools/make_lang_list ../flite_V26/hear2read/flite/tools/make_lang_list
diff lang ../flite_V26/hear2read/flite/lang
diff lang/cmu_us_rms ../flite_V26/hear2read/flite/lang/cmu_us_rms
diff lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.c
diff lang/cmu_us_rms/cmu_us_rms_voice.cpp ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_voice.cpp
diff lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.h
diff lang/cmu_us_rms/cmu_us_rms.vcproj ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms.vcproj
diff lang/cmu_us_rms/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/voxdefs.h
diff lang/cmu_us_rms/stdafx.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/stdafx.h
diff lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.c
diff lang/cmu_us_rms/cmu_us_rms_spamf0_accent.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_spamf0_accent.h
diff lang/cmu_us_rms/Exports.def ../flite_V26/hear2read/flite/lang/cmu_us_rms/Exports.def
diff lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_f0_trees.h
diff lang/cmu_us_rms/Makefile ../flite_V26/hear2read/flite/lang/cmu_us_rms/Makefile
diff lang/cmu_us_rms/cmu_us_rms_cg_durmodel.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_durmodel.c
diff lang/cmu_us_rms/cmu_us_rms_cg_single_params.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_single_params.c
diff lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_spamf0_phrase.h
diff lang/cmu_us_rms/cmu_us_rms_spamf0_accent.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_spamf0_accent.c
diff lang/cmu_us_rms/cmu_us_rms_cg_phonestate.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_phonestate.c
diff lang/cmu_us_rms/cmu_us_rms_cg.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg.c
diff lang/cmu_us_rms/cmu_us_rms.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms.c
diff lang/cmu_us_rms/cmu_us_rms_spamf0_accent_params.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_spamf0_accent_params.c
diff lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_single_mcep_trees.c
diff lang/cmu_us_rms/cmu_us_rms_cg_durmodel.h ../flite_V26/hear2read/flite/lang/cmu_us_rms/cmu_us_rms_cg_durmodel.h
diff lang/cmu_grapheme_lang ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang
diff lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.h ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.h
diff lang/cmu_grapheme_lang/cmu_grapheme_lang.c ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/cmu_grapheme_lang.c
diff lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.c ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/cmu_grapheme_phrasing_cart.c
diff lang/cmu_grapheme_lang/cmu_grapheme_phoneset.c ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/cmu_grapheme_phoneset.c
diff lang/cmu_grapheme_lang/Makefile ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/Makefile
diff lang/cmu_grapheme_lang/make_grapheme_phoneset ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/make_grapheme_phoneset
diff lang/cmu_grapheme_lang/cmu_grapheme_lang.h ../flite_V26/hear2read/flite/lang/cmu_grapheme_lang/cmu_grapheme_lang.h
diff lang/cmu_time_awb ../flite_V26/hear2read/flite/lang/cmu_time_awb
diff lang/cmu_time_awb/cmu_time_awb_lpc.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb_lpc.c
diff lang/cmu_time_awb/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_time_awb/voxdefs.h
diff lang/cmu_time_awb/cmu_time_awb_mcep.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb_mcep.c
diff lang/cmu_time_awb/Makefile ../flite_V26/hear2read/flite/lang/cmu_time_awb/Makefile
diff lang/cmu_time_awb/cmu_time_awb_lex_entry.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb_lex_entry.c
diff lang/cmu_time_awb/cmu_time_awb.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb.c
diff lang/cmu_time_awb/cmu_time_awb_cart.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb_cart.c
diff lang/cmu_time_awb/cmu_time_awb_clunits.c ../flite_V26/hear2read/flite/lang/cmu_time_awb/cmu_time_awb_clunits.c
diff lang/usenglish ../flite_V26/hear2read/flite/lang/usenglish
diff lang/usenglish/usenglish.h ../flite_V26/hear2read/flite/lang/usenglish/usenglish.h
diff lang/usenglish/us_text.c ../flite_V26/hear2read/flite/lang/usenglish/us_text.c
diff lang/usenglish/us_phrasing_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_phrasing_cart.c
diff lang/usenglish/usenglish.c ../flite_V26/hear2read/flite/lang/usenglish/usenglish.c
diff lang/usenglish/us_durz_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_durz_cart.c
diff lang/usenglish/us_phrasing_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_phrasing_cart.h
diff lang/usenglish/us_f0_model.c ../flite_V26/hear2read/flite/lang/usenglish/us_f0_model.c
diff lang/usenglish/us_phoneset.c ../flite_V26/hear2read/flite/lang/usenglish/us_phoneset.c
diff lang/usenglish/us_durz_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_durz_cart.h
diff lang/usenglish/libflite-usenglish.vcproj ../flite_V26/hear2read/flite/lang/usenglish/libflite-usenglish.vcproj
diff lang/usenglish/Makefile ../flite_V26/hear2read/flite/lang/usenglish/Makefile
diff lang/usenglish/us_aswd.c ../flite_V26/hear2read/flite/lang/usenglish/us_aswd.c
diff lang/usenglish/make_us_regexes ../flite_V26/hear2read/flite/lang/usenglish/make_us_regexes
diff lang/usenglish/us_gpos.c ../flite_V26/hear2read/flite/lang/usenglish/us_gpos.c
diff lang/usenglish/us_ffeatures.h ../flite_V26/hear2read/flite/lang/usenglish/us_ffeatures.h
diff lang/usenglish/us_ffeatures.c ../flite_V26/hear2read/flite/lang/usenglish/us_ffeatures.c
diff lang/usenglish/us_nums_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_nums_cart.h
diff lang/usenglish/us_expand.c ../flite_V26/hear2read/flite/lang/usenglish/us_expand.c
diff lang/usenglish/us_dur_stats.c ../flite_V26/hear2read/flite/lang/usenglish/us_dur_stats.c
diff lang/usenglish/us_pos.tree ../flite_V26/hear2read/flite/lang/usenglish/us_pos.tree
diff lang/usenglish/us_nums_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_nums_cart.c
diff lang/usenglish/us_f0.h ../flite_V26/hear2read/flite/lang/usenglish/us_f0.h
diff lang/usenglish/us_int_accent_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_int_accent_cart.h
diff lang/usenglish/us_text.h ../flite_V26/hear2read/flite/lang/usenglish/us_text.h
diff lang/usenglish/us_f0lr.c ../flite_V26/hear2read/flite/lang/usenglish/us_f0lr.c
diff lang/usenglish/us_int_tone_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_int_tone_cart.h
diff lang/usenglish/us_pos_cart.h ../flite_V26/hear2read/flite/lang/usenglish/us_pos_cart.h
diff lang/usenglish/us_int_accent_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_int_accent_cart.c
diff lang/usenglish/us_regexes.h ../flite_V26/hear2read/flite/lang/usenglish/us_regexes.h
diff lang/usenglish/us_pos_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_pos_cart.c
diff lang/usenglish/us_int_tone_cart.c ../flite_V26/hear2read/flite/lang/usenglish/us_int_tone_cart.c
diff lang/Makefile ../flite_V26/hear2read/flite/lang/Makefile
diff lang/cmu_indic_lang ../flite_V26/hear2read/flite/lang/cmu_indic_lang
diff lang/cmu_indic_lang/indic_mal_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_mal_num_table.h
diff lang/cmu_indic_lang/indic_san_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_san_num_table.h
diff lang/cmu_indic_lang/cmu_indic_phrasing_cart.c ../flite_V26/hear2read/flite/lang/cmu_indic_lang/cmu_indic_phrasing_cart.c
diff lang/cmu_indic_lang/indic_kan_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_kan_num_table.h
diff lang/cmu_indic_lang/indic_tam_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_tam_num_table.h
diff lang/cmu_indic_lang/cmu_indic_phoneset.c ../flite_V26/hear2read/flite/lang/cmu_indic_lang/cmu_indic_phoneset.c
diff lang/cmu_indic_lang/Makefile ../flite_V26/hear2read/flite/lang/cmu_indic_lang/Makefile
diff lang/cmu_indic_lang/cmu_indic_phrasing_cart.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/cmu_indic_phrasing_cart.h
diff lang/cmu_indic_lang/indic_pan_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_pan_num_table.h
diff lang/cmu_indic_lang/indic_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_num_table.h
diff lang/cmu_indic_lang/cmu_indic_lang.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/cmu_indic_lang.h
diff lang/cmu_indic_lang/indic_tel_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_tel_num_table.h
diff lang/cmu_indic_lang/indic_asm_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_asm_num_table.h
diff lang/cmu_indic_lang/indic_hin_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_hin_num_table.h
diff lang/cmu_indic_lang/indic_mar_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_mar_num_table.h
diff lang/cmu_indic_lang/indic_guj_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_guj_num_table.h
diff lang/cmu_indic_lang/indic_eng_num_table.h ../flite_V26/hear2read/flite/lang/cmu_indic_lang/indic_eng_num_table.h
diff lang/cmu_indic_lang/cmu_indic_lang.c ../flite_V26/hear2read/flite/lang/cmu_indic_lang/cmu_indic_lang.c
diff lang/cmu_us_kal16 ../flite_V26/hear2read/flite/lang/cmu_us_kal16
diff lang/cmu_us_kal16/cmu_us_kal16.c ../flite_V26/hear2read/flite/lang/cmu_us_kal16/cmu_us_kal16.c
diff lang/cmu_us_kal16/cmu_us_kal16_diphone.c ../flite_V26/hear2read/flite/lang/cmu_us_kal16/cmu_us_kal16_diphone.c
diff lang/cmu_us_kal16/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_us_kal16/voxdefs.h
diff lang/cmu_us_kal16/cmu_us_kal16_res.c ../flite_V26/hear2read/flite/lang/cmu_us_kal16/cmu_us_kal16_res.c
diff lang/cmu_us_kal16/cmu_us_kal16_residx.c ../flite_V26/hear2read/flite/lang/cmu_us_kal16/cmu_us_kal16_residx.c
diff lang/cmu_us_kal16/cmu_us_kal16_lpc.c ../flite_V26/hear2read/flite/lang/cmu_us_kal16/cmu_us_kal16_lpc.c
diff lang/cmu_us_kal16/Makefile ../flite_V26/hear2read/flite/lang/cmu_us_kal16/Makefile
diff lang/cmu_us_kal ../flite_V26/hear2read/flite/lang/cmu_us_kal
diff lang/cmu_us_kal/cmu_us_kal_lpc.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal_lpc.c
diff lang/cmu_us_kal/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_us_kal/voxdefs.h
diff lang/cmu_us_kal/cmu_us_kal_ressize.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal_ressize.c
diff lang/cmu_us_kal/Makefile ../flite_V26/hear2read/flite/lang/cmu_us_kal/Makefile
diff lang/cmu_us_kal/cmu_us_kal_res.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal_res.c
diff lang/cmu_us_kal/cmu_us_kal_diphone.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal_diphone.c
diff lang/cmu_us_kal/cmu_us_kal_residx.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal_residx.c
diff lang/cmu_us_kal/cmu_us_kal.c ../flite_V26/hear2read/flite/lang/cmu_us_kal/cmu_us_kal.c
diff lang/cmulex ../flite_V26/hear2read/flite/lang/cmulex
diff lang/cmulex/cmu_lex_entries.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_entries.c
diff lang/cmulex/cmu_lts_model.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lts_model.c
diff lang/cmulex/cmu_lts_model.h ../flite_V26/hear2read/flite/lang/cmulex/cmu_lts_model.h
diff lang/cmulex/cmu_lex.h ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex.h
diff lang/cmulex/cmu_lex_phones_huff_table.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_phones_huff_table.c
diff lang/cmulex/Makefile ../flite_V26/hear2read/flite/lang/cmulex/Makefile
diff lang/cmulex/cmu_lex.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex.c
diff lang/cmulex/libflite-cmulex.vcproj ../flite_V26/hear2read/flite/lang/cmulex/libflite-cmulex.vcproj
diff lang/cmulex/cmu_lts_rules.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lts_rules.c
diff lang/cmulex/cmu_lex_entries_huff_table.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_entries_huff_table.c
diff lang/cmulex/cmu_lex_data.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_data.c
diff lang/cmulex/cmu_lex_num_bytes.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_num_bytes.c
diff lang/cmulex/cmu_postlex.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_postlex.c
diff lang/cmulex/cmu_lex_data_raw.c ../flite_V26/hear2read/flite/lang/cmulex/cmu_lex_data_raw.c
diff lang/cmulex/make_cmulex ../flite_V26/hear2read/flite/lang/cmulex/make_cmulex
diff lang/cmu_grapheme_lex ../flite_V26/hear2read/flite/lang/cmu_grapheme_lex
diff lang/cmu_grapheme_lex/cmu_grapheme_lex.h ../flite_V26/hear2read/flite/lang/cmu_grapheme_lex/cmu_grapheme_lex.h
diff lang/cmu_grapheme_lex/Makefile ../flite_V26/hear2read/flite/lang/cmu_grapheme_lex/Makefile
diff lang/cmu_grapheme_lex/grapheme_unitran_tables.c ../flite_V26/hear2read/flite/lang/cmu_grapheme_lex/grapheme_unitran_tables.c
diff lang/cmu_grapheme_lex/cmu_grapheme_lex.c ../flite_V26/hear2read/flite/lang/cmu_grapheme_lex/cmu_grapheme_lex.c
diff lang/cmu_us_slt ../flite_V26/hear2read/flite/lang/cmu_us_slt
diff lang/cmu_us_slt/cmu_us_slt_cg_single_params.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_single_params.c
diff lang/cmu_us_slt/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/voxdefs.h
diff lang/cmu_us_slt/cmu_us_slt_cg_phonestate.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_phonestate.c
diff lang/cmu_us_slt/cmu_us_slt.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt.c
diff lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.c
diff lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_spamf0_phrase.h
diff lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.h
diff lang/cmu_us_slt/cmu_us_slt_spamf0_accent.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_spamf0_accent.c
diff lang/cmu_us_slt/Makefile ../flite_V26/hear2read/flite/lang/cmu_us_slt/Makefile
diff lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_single_mcep_trees.c
diff lang/cmu_us_slt/cmu_us_slt_cg_durmodel.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_durmodel.c
diff lang/cmu_us_slt/cmu_us_slt_cg.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg.c
diff lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.h
diff lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_f0_trees.c
diff lang/cmu_us_slt/cmu_us_slt_spamf0_accent.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_spamf0_accent.h
diff lang/cmu_us_slt/cmu_us_slt_spamf0_accent_params.c ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_spamf0_accent_params.c
diff lang/cmu_us_slt/cmu_us_slt_cg_durmodel.h ../flite_V26/hear2read/flite/lang/cmu_us_slt/cmu_us_slt_cg_durmodel.h
diff lang/cmu_us_awb ../flite_V26/hear2read/flite/lang/cmu_us_awb
diff lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.h
diff lang/cmu_us_awb/voxdefs.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/voxdefs.h
diff lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.c
diff lang/cmu_us_awb/cmu_us_awb.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb.c
diff lang/cmu_us_awb/cmu_us_awb_cg_phonestate.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_phonestate.c
diff lang/cmu_us_awb/cmu_us_awb_cg_single_params.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_single_params.c
diff lang/cmu_us_awb/Makefile ../flite_V26/hear2read/flite/lang/cmu_us_awb/Makefile
diff lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_spamf0_phrase.c
diff lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.h
diff lang/cmu_us_awb/cmu_us_awb_cg.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg.c
diff lang/cmu_us_awb/cmu_us_awb_cg_durmodel.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_durmodel.c
diff lang/cmu_us_awb/cmu_us_awb_spamf0_accent_params.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_spamf0_accent_params.c
diff lang/cmu_us_awb/cmu_us_awb_spamf0_accent.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_spamf0_accent.h
diff lang/cmu_us_awb/cmu_us_awb_spamf0_accent.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_spamf0_accent.c
diff lang/cmu_us_awb/cmu_us_awb_cg_durmodel.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_durmodel.h
diff lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.h ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_single_mcep_trees.h
diff lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.c ../flite_V26/hear2read/flite/lang/cmu_us_awb/cmu_us_awb_cg_f0_trees.c
diff lang/cmu_indic_lex ../flite_V26/hear2read/flite/lang/cmu_indic_lex
diff lang/cmu_indic_lex/cmu_indic_lex.c ../flite_V26/hear2read/flite/lang/cmu_indic_lex/cmu_indic_lex.c
diff lang/cmu_indic_lex/Makefile ../flite_V26/hear2read/flite/lang/cmu_indic_lex/Makefile
diff lang/cmu_indic_lex/cmu_indic_lex.h ../flite_V26/hear2read/flite/lang/cmu_indic_lex/cmu_indic_lex.h
diff lang/cmu_indic_lex/cmu_indic_lex.c.save ../flite_V26/hear2read/flite/lang/cmu_indic_lex/cmu_indic_lex.c.save
diff flite-master ../flite_V26/hear2read/flite/flite-master
diff fliteDll.vcxproj ../flite_V26/hear2read/flite/fliteDll.vcxproj
diff windows ../flite_V26/hear2read/flite/windows
diff windows/fliteDll.cpp ../flite_V26/hear2read/flite/windows/fliteDll.cpp
diff windows/stdafx.h ../flite_V26/hear2read/flite/windows/stdafx.h
diff windows/Makefile ../flite_V26/hear2read/flite/windows/Makefile
diff src ../flite_V26/hear2read/flite/src
diff src/lexicon ../flite_V26/hear2read/flite/src/lexicon
diff src/lexicon/cst_lts.c ../flite_V26/hear2read/flite/src/lexicon/cst_lts.c
diff src/lexicon/Makefile ../flite_V26/hear2read/flite/src/lexicon/Makefile
diff src/lexicon/cst_lts_rewrites.c ../flite_V26/hear2read/flite/src/lexicon/cst_lts_rewrites.c
diff src/lexicon/cst_lexicon.c ../flite_V26/hear2read/flite/src/lexicon/cst_lexicon.c
diff src/utils ../flite_V26/hear2read/flite/src/utils
diff src/utils/cst_tokenstream.c ../flite_V26/hear2read/flite/src/utils/cst_tokenstream.c
diff src/utils/cst_mmap_none.c ../flite_V26/hear2read/flite/src/utils/cst_mmap_none.c
diff src/utils/cst_mmap_win32.c ../flite_V26/hear2read/flite/src/utils/cst_mmap_win32.c
diff src/utils/cst_file_palmos.c ../flite_V26/hear2read/flite/src/utils/cst_file_palmos.c
diff src/utils/Makefile ../flite_V26/hear2read/flite/src/utils/Makefile
diff src/utils/cst_features.c ../flite_V26/hear2read/flite/src/utils/cst_features.c
diff src/utils/cst_val_const.c ../flite_V26/hear2read/flite/src/utils/cst_val_const.c
diff src/utils/cst_file_stdio.c ../flite_V26/hear2read/flite/src/utils/cst_file_stdio.c
diff src/utils/cst_url.c ../flite_V26/hear2read/flite/src/utils/cst_url.c
diff src/utils/cst_val.c ../flite_V26/hear2read/flite/src/utils/cst_val.c
diff src/utils/cst_wchar.c ../flite_V26/hear2read/flite/src/utils/cst_wchar.c
diff src/utils/cst_string.c ../flite_V26/hear2read/flite/src/utils/cst_string.c
diff src/utils/cst_endian.c ../flite_V26/hear2read/flite/src/utils/cst_endian.c
diff src/utils/cst_mmap_posix.c ../flite_V26/hear2read/flite/src/utils/cst_mmap_posix.c
diff src/utils/cst_alloc.c ../flite_V26/hear2read/flite/src/utils/cst_alloc.c
diff src/utils/cst_file_wince.c ../flite_V26/hear2read/flite/src/utils/cst_file_wince.c
diff src/utils/cst_args.c ../flite_V26/hear2read/flite/src/utils/cst_args.c
diff src/utils/cst_socket.c ../flite_V26/hear2read/flite/src/utils/cst_socket.c
diff src/utils/cst_val_user.c ../flite_V26/hear2read/flite/src/utils/cst_val_user.c
diff src/utils/cst_error.c ../flite_V26/hear2read/flite/src/utils/cst_error.c
diff src/wavesynth ../flite_V26/hear2read/flite/src/wavesynth
diff src/wavesynth/cst_diphone.c ../flite_V26/hear2read/flite/src/wavesynth/cst_diphone.c
diff src/wavesynth/cst_clunits.c ../flite_V26/hear2read/flite/src/wavesynth/cst_clunits.c
diff src/wavesynth/Makefile ../flite_V26/hear2read/flite/src/wavesynth/Makefile
diff src/wavesynth/cst_reflpc.c ../flite_V26/hear2read/flite/src/wavesynth/cst_reflpc.c
diff src/wavesynth/cst_sts.c ../flite_V26/hear2read/flite/src/wavesynth/cst_sts.c
diff src/wavesynth/cst_units.c ../flite_V26/hear2read/flite/src/wavesynth/cst_units.c
diff src/wavesynth/cst_sigpr.c ../flite_V26/hear2read/flite/src/wavesynth/cst_sigpr.c
diff src/synth ../flite_V26/hear2read/flite/src/synth
diff src/synth/cst_utt_utils.c ../flite_V26/hear2read/flite/src/synth/cst_utt_utils.c
diff src/synth/Makefile ../flite_V26/hear2read/flite/src/synth/Makefile
diff src/synth/flite.c ../flite_V26/hear2read/flite/src/synth/flite.c
diff src/synth/cst_voice.c ../flite_V26/hear2read/flite/src/synth/cst_voice.c
diff src/synth/cst_synth.c ../flite_V26/hear2read/flite/src/synth/cst_synth.c
diff src/synth/cst_ffeatures.c ../flite_V26/hear2read/flite/src/synth/cst_ffeatures.c
diff src/synth/cst_ssml.c ../flite_V26/hear2read/flite/src/synth/cst_ssml.c
diff src/synth/cst_phoneset.c ../flite_V26/hear2read/flite/src/synth/cst_phoneset.c
diff src/stats ../flite_V26/hear2read/flite/src/stats
diff src/stats/cst_viterbi.c ../flite_V26/hear2read/flite/src/stats/cst_viterbi.c
diff src/stats/cst_cart.c ../flite_V26/hear2read/flite/src/stats/cst_cart.c
diff src/stats/cst_ss.c ../flite_V26/hear2read/flite/src/stats/cst_ss.c
diff src/stats/Makefile ../flite_V26/hear2read/flite/src/stats/Makefile
diff src/audio ../flite_V26/hear2read/flite/src/audio
diff src/audio/au_palmos.c ../flite_V26/hear2read/flite/src/audio/au_palmos.c
diff src/audio/au_win.c ../flite_V26/hear2read/flite/src/audio/au_win.c
diff src/audio/auserver.c ../flite_V26/hear2read/flite/src/audio/auserver.c
diff src/audio/native_audio.h ../flite_V26/hear2read/flite/src/audio/native_audio.h
diff src/audio/au_wince.c ../flite_V26/hear2read/flite/src/audio/au_wince.c
diff src/audio/Makefile ../flite_V26/hear2read/flite/src/audio/Makefile
diff src/audio/au_sun.c ../flite_V26/hear2read/flite/src/audio/au_sun.c
diff src/audio/au_none.c ../flite_V26/hear2read/flite/src/audio/au_none.c
diff src/audio/audio.c ../flite_V26/hear2read/flite/src/audio/audio.c
diff src/audio/auclient.c ../flite_V26/hear2read/flite/src/audio/auclient.c
diff src/audio/au_command.c ../flite_V26/hear2read/flite/src/audio/au_command.c
diff src/audio/au_streaming.c ../flite_V26/hear2read/flite/src/audio/au_streaming.c
diff src/audio/au_pulseaudio.c ../flite_V26/hear2read/flite/src/audio/au_pulseaudio.c
diff src/audio/au_oss.c ../flite_V26/hear2read/flite/src/audio/au_oss.c
diff src/audio/au_alsa.c ../flite_V26/hear2read/flite/src/audio/au_alsa.c
diff src/Makefile ../flite_V26/hear2read/flite/src/Makefile
diff src/speech ../flite_V26/hear2read/flite/src/speech
diff src/speech/rateconv.c ../flite_V26/hear2read/flite/src/speech/rateconv.c
diff src/speech/cst_track.c ../flite_V26/hear2read/flite/src/speech/cst_track.c
diff src/speech/cst_wave_io.c ../flite_V26/hear2read/flite/src/speech/cst_wave_io.c
diff src/speech/g72x.c ../flite_V26/hear2read/flite/src/speech/g72x.c
diff src/speech/Makefile ../flite_V26/hear2read/flite/src/speech/Makefile
diff src/speech/cst_wave.c ../flite_V26/hear2read/flite/src/speech/cst_wave.c
diff src/speech/cst_lpcres.c ../flite_V26/hear2read/flite/src/speech/cst_lpcres.c
diff src/speech/g723_40.c ../flite_V26/hear2read/flite/src/speech/g723_40.c
diff src/speech/g72x.h ../flite_V26/hear2read/flite/src/speech/g72x.h
diff src/speech/cst_track_io.c ../flite_V26/hear2read/flite/src/speech/cst_track_io.c
diff src/speech/g723_24.c ../flite_V26/hear2read/flite/src/speech/g723_24.c
diff src/speech/cst_wave_utils.c ../flite_V26/hear2read/flite/src/speech/cst_wave_utils.c
diff src/speech/g721.c ../flite_V26/hear2read/flite/src/speech/g721.c
diff src/hrg ../flite_V26/hear2read/flite/src/hrg
diff src/hrg/cst_item.c ../flite_V26/hear2read/flite/src/hrg/cst_item.c
diff src/hrg/cst_ffeature.c ../flite_V26/hear2read/flite/src/hrg/cst_ffeature.c
diff src/hrg/cst_utterance.c ../flite_V26/hear2read/flite/src/hrg/cst_utterance.c
diff src/hrg/cst_rel_io.c ../flite_V26/hear2read/flite/src/hrg/cst_rel_io.c
diff src/hrg/Makefile ../flite_V26/hear2read/flite/src/hrg/Makefile
diff src/hrg/cst_relation.c ../flite_V26/hear2read/flite/src/hrg/cst_relation.c
diff src/regex ../flite_V26/hear2read/flite/src/regex
diff src/regex/cst_regex_defs.h ../flite_V26/hear2read/flite/src/regex/cst_regex_defs.h
diff src/regex/Makefile ../flite_V26/hear2read/flite/src/regex/Makefile
diff src/regex/regexp.c ../flite_V26/hear2read/flite/src/regex/regexp.c
diff src/regex/regsub.c ../flite_V26/hear2read/flite/src/regex/regsub.c
diff src/regex/cst_regex.c ../flite_V26/hear2read/flite/src/regex/cst_regex.c
diff src/cg ../flite_V26/hear2read/flite/src/cg
diff src/cg/cst_mlsa.h ../flite_V26/hear2read/flite/src/cg/cst_mlsa.h
diff src/cg/cst_mlsa.c ../flite_V26/hear2read/flite/src/cg/cst_mlsa.c
diff src/cg/cst_vc.h ../flite_V26/hear2read/flite/src/cg/cst_vc.h
diff src/cg/cst_spamf0.c ../flite_V26/hear2read/flite/src/cg/cst_spamf0.c
diff src/cg/Makefile ../flite_V26/hear2read/flite/src/cg/Makefile
diff src/cg/cst_cg_load_voice.c ../flite_V26/hear2read/flite/src/cg/cst_cg_load_voice.c
diff src/cg/cst_cg_map.c ../flite_V26/hear2read/flite/src/cg/cst_cg_map.c
diff src/cg/cst_vc.c ../flite_V26/hear2read/flite/src/cg/cst_vc.c
diff src/cg/cst_mlpg.c ../flite_V26/hear2read/flite/src/cg/cst_mlpg.c
diff src/cg/cst_cg_map.h ../flite_V26/hear2read/flite/src/cg/cst_cg_map.h
diff src/cg/cst_spamf0.h ../flite_V26/hear2read/flite/src/cg/cst_spamf0.h
diff src/cg/cst_cg.c ../flite_V26/hear2read/flite/src/cg/cst_cg.c
diff src/cg/cst_cg_dump_voice.c ../flite_V26/hear2read/flite/src/cg/cst_cg_dump_voice.c
diff src/cg/cst_mlpg.h ../flite_V26/hear2read/flite/src/cg/cst_mlpg.h
diff README.md ../flite_V26/hear2read/flite/README.md
diff testsuite ../flite_V26/hear2read/flite/testsuite
diff testsuite/lex_lookup_main.c ../flite_V26/hear2read/flite/testsuite/lex_lookup_main.c
diff testsuite/indic_tam.flitecheck ../flite_V26/hear2read/flite/testsuite/indic_tam.flitecheck
diff testsuite/utt_test_main.c ../flite_V26/hear2read/flite/testsuite/utt_test_main.c
diff testsuite/asciiU2S_main.c ../flite_V26/hear2read/flite/testsuite/asciiU2S_main.c
diff testsuite/asciiS2U_main.c ../flite_V26/hear2read/flite/testsuite/asciiS2U_main.c
diff testsuite/combine_waves_main.c ../flite_V26/hear2read/flite/testsuite/combine_waves_main.c
diff testsuite/play_wave_main.c ../flite_V26/hear2read/flite/testsuite/play_wave_main.c
diff testsuite/by_word_main.c ../flite_V26/hear2read/flite/testsuite/by_word_main.c
diff testsuite/us.flitecheck ../flite_V26/hear2read/flite/testsuite/us.flitecheck
diff testsuite/regex_test_main.c ../flite_V26/hear2read/flite/testsuite/regex_test_main.c
diff testsuite/record_wave_main.c ../flite_V26/hear2read/flite/testsuite/record_wave_main.c
diff testsuite/nums_test_main.c ../flite_V26/hear2read/flite/testsuite/nums_test_main.c
diff testsuite/token_test_main.c ../flite_V26/hear2read/flite/testsuite/token_test_main.c
diff testsuite/multi_thread_main.c ../flite_V26/hear2read/flite/testsuite/multi_thread_main.c
diff testsuite/Makefile ../flite_V26/hear2read/flite/testsuite/Makefile
diff testsuite/lpc_resynth_main.c ../flite_V26/hear2read/flite/testsuite/lpc_resynth_main.c
diff testsuite/record_in_noise_main.c ../flite_V26/hear2read/flite/testsuite/record_in_noise_main.c
diff testsuite/bin2ascii_main.c ../flite_V26/hear2read/flite/testsuite/bin2ascii_main.c
diff testsuite/lpc_test_main.c ../flite_V26/hear2read/flite/testsuite/lpc_test_main.c
diff testsuite/compare_wave_main.c ../flite_V26/hear2read/flite/testsuite/compare_wave_main.c
diff testsuite/dcoffset_wave_main.c ../flite_V26/hear2read/flite/testsuite/dcoffset_wave_main.c
diff testsuite/tris1_main.c ../flite_V26/hear2read/flite/testsuite/tris1_main.c
diff testsuite/kal_test_main.c ../flite_V26/hear2read/flite/testsuite/kal_test_main.c
diff testsuite/indic_hin.flitecheck ../flite_V26/hear2read/flite/testsuite/indic_hin.flitecheck
diff testsuite/play_sync_main.c ../flite_V26/hear2read/flite/testsuite/play_sync_main.c
diff testsuite/play_server_main.c ../flite_V26/hear2read/flite/testsuite/play_server_main.c
diff testsuite/lex_test_main.c ../flite_V26/hear2read/flite/testsuite/lex_test_main.c
diff testsuite/data.one ../flite_V26/hear2read/flite/testsuite/data.one
diff testsuite/lpc_test2_main.c ../flite_V26/hear2read/flite/testsuite/lpc_test2_main.c
diff testsuite/rfc_main.c ../flite_V26/hear2read/flite/testsuite/rfc_main.c
diff testsuite/flite_test_main.c ../flite_V26/hear2read/flite/testsuite/flite_test_main.c
diff testsuite/play_client_main.c ../flite_V26/hear2read/flite/testsuite/play_client_main.c
diff testsuite/hrg_test_main.c ../flite_V26/hear2read/flite/testsuite/hrg_test_main.c
diff doc ../flite_V26/hear2read/flite/doc
diff doc/intro.txt ../flite_V26/hear2read/flite/doc/intro.txt
diff doc/Makefile ../flite_V26/hear2read/flite/doc/Makefile
diff doc/stuff.ed ../flite_V26/hear2read/flite/doc/stuff.ed
diff doc/flite.texi ../flite_V26/hear2read/flite/doc/flite.texi
diff doc/alice ../flite_V26/hear2read/flite/doc/alice
